-- =====================================================================
--  SOMAR Electrodomésticos — Migración inicial del CMS
--  Schema exclusivo del proyecto: somarelectrodomesticos
--  Todas las tablas de negocio viven dentro de este schema.
--  (auth / storage son internos de Supabase y NO se tocan.)
-- =====================================================================

create schema if not exists somarelectrodomesticos;

-- Extensiones útiles (por si no están)
create extension if not exists pgcrypto;

-- is_admin() referencia admin_users, que se crea más abajo. Con esto Postgres
-- NO valida el cuerpo de las funciones al crearlas (se valida en runtime, cuando
-- la tabla ya existe). Evita el error 42P01 al ejecutar toda la migración de una.
set check_function_bodies = off;

-- ---------------------------------------------------------------------
--  Función reutilizable: updated_at automático
-- ---------------------------------------------------------------------
create or replace function somarelectrodomesticos.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------
--  Función de seguridad: ¿el usuario actual es admin activo?
--  SECURITY DEFINER para poder leer admin_users saltando su RLS.
-- ---------------------------------------------------------------------
create or replace function somarelectrodomesticos.is_admin()
returns boolean
language sql
stable
security definer
set search_path = somarelectrodomesticos, public
as $$
  select exists (
    select 1
    from somarelectrodomesticos.admin_users au
    where au.user_id = auth.uid()
      and au.is_active = true
  );
$$;

-- =====================================================================
--  TABLAS
-- =====================================================================

-- 1) ADMIN USERS -------------------------------------------------------
create table if not exists somarelectrodomesticos.admin_users (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null unique references auth.users(id) on delete cascade,
  full_name   text,
  role        text not null default 'admin' check (role in ('superadmin','admin','editor')),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 2) SITE SETTINGS (singleton) ----------------------------------------
create table if not exists somarelectrodomesticos.site_settings (
  id                        bigint generated by default as identity primary key,
  business_name             text not null default 'SOMAR Electrodomésticos',
  slogan                    text,
  logo_url                  text,
  whatsapp_primary          text,
  whatsapp_secondary        text,
  facebook_url              text,
  instagram_url             text,
  email                     text,
  address                   text,
  currency                  text not null default 'PYG',
  currency_symbol           text not null default 'Gs.',
  default_installment_rate  numeric(6,4) not null default 0.0640,
  default_max_installments  int not null default 12,
  low_stock_threshold       int not null default 3,
  seo_title                 text,
  seo_description           text,
  footer_text               text,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

-- 3) CATEGORIES --------------------------------------------------------
create table if not exists somarelectrodomesticos.categories (
  id             bigint generated by default as identity primary key,
  name           text not null,
  slug           text not null unique,
  description    text,
  icon           text,
  accent_color   text,
  image_url      text,
  display_order  int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 4) BRANDS ------------------------------------------------------------
create table if not exists somarelectrodomesticos.brands (
  id             bigint generated by default as identity primary key,
  name           text not null,
  slug           text not null unique,
  logo_url       text,
  description    text,
  display_order  int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 5) PRODUCTS ----------------------------------------------------------
--  IDs BIGINT preservando los IDs actuales (1..18) para no romper
--  carrito/favoritos guardados en localStorage.
create table if not exists somarelectrodomesticos.products (
  id                bigint generated by default as identity primary key,
  sku               text,
  slug              text not null unique,
  name              text not null,
  category_id       bigint references somarelectrodomesticos.categories(id) on delete set null,
  brand_id          bigint references somarelectrodomesticos.brands(id) on delete set null,
  color             text,
  short_description text,
  description       text,
  price             numeric(14,2) not null default 0 check (price >= 0),
  previous_price    numeric(14,2) check (previous_price >= 0),
  stock             int not null default 0 check (stock >= 0),
  badge             text,
  is_active         boolean not null default true,
  is_featured       boolean not null default false,
  is_best_seller    boolean not null default false,
  is_new            boolean not null default false,
  display_order     int not null default 0,
  installment_rate  numeric(6,4),
  max_installments  int not null default 12,
  warranty_months   int,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists idx_products_slug          on somarelectrodomesticos.products(slug);
create index if not exists idx_products_category      on somarelectrodomesticos.products(category_id);
create index if not exists idx_products_brand         on somarelectrodomesticos.products(brand_id);
create index if not exists idx_products_active        on somarelectrodomesticos.products(is_active);
create index if not exists idx_products_featured      on somarelectrodomesticos.products(is_featured);
create index if not exists idx_products_best_seller   on somarelectrodomesticos.products(is_best_seller);
create index if not exists idx_products_display_order on somarelectrodomesticos.products(display_order);

-- 6) PRODUCT IMAGES ----------------------------------------------------
create table if not exists somarelectrodomesticos.product_images (
  id             bigint generated by default as identity primary key,
  product_id     bigint not null references somarelectrodomesticos.products(id) on delete cascade,
  image_url      text not null,
  storage_path   text,
  alt_text       text,
  is_primary     boolean not null default false,
  display_order  int not null default 0,
  created_at     timestamptz not null default now()
);
create index if not exists idx_product_images_product on somarelectrodomesticos.product_images(product_id);

-- 7) PRODUCT FEATURES --------------------------------------------------
create table if not exists somarelectrodomesticos.product_features (
  id             bigint generated by default as identity primary key,
  product_id     bigint not null references somarelectrodomesticos.products(id) on delete cascade,
  feature        text not null,
  display_order  int not null default 0
);
create index if not exists idx_product_features_product on somarelectrodomesticos.product_features(product_id);

-- 8) PRODUCT SPECIFICATIONS -------------------------------------------
create table if not exists somarelectrodomesticos.product_specifications (
  id             bigint generated by default as identity primary key,
  product_id     bigint not null references somarelectrodomesticos.products(id) on delete cascade,
  label          text not null,
  value          text not null,
  display_order  int not null default 0
);
create index if not exists idx_product_specs_product on somarelectrodomesticos.product_specifications(product_id);

-- 9) PRODUCT INSTALLMENTS (overrides de cuotas) -----------------------
create table if not exists somarelectrodomesticos.product_installments (
  id            bigint generated by default as identity primary key,
  product_id    bigint not null references somarelectrodomesticos.products(id) on delete cascade,
  installments  int not null check (installments >= 1),
  amount        numeric(14,2) not null check (amount >= 0),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (product_id, installments)
);
create index if not exists idx_product_installments_product on somarelectrodomesticos.product_installments(product_id);

-- 10) BENEFITS ---------------------------------------------------------
create table if not exists somarelectrodomesticos.benefits (
  id             bigint generated by default as identity primary key,
  title          text not null,
  icon           text,
  display_order  int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 11) PURCHASE STEPS ---------------------------------------------------
create table if not exists somarelectrodomesticos.purchase_steps (
  id             bigint generated by default as identity primary key,
  step_number    int not null,
  title          text not null,
  description    text,
  accent_color   text,
  display_order  int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 12) TESTIMONIALS -----------------------------------------------------
create table if not exists somarelectrodomesticos.testimonials (
  id             bigint generated by default as identity primary key,
  customer_name  text not null,
  review         text not null,
  rating         int not null default 5 check (rating between 1 and 5),
  avatar_url     text,
  display_order  int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 13) STATS ------------------------------------------------------------
create table if not exists somarelectrodomesticos.stats (
  id             bigint generated by default as identity primary key,
  value          text not null,
  label          text not null,
  display_order  int not null default 0,
  is_active      boolean not null default true
);

-- 14) SOCIAL POSTS / GALERÍA ------------------------------------------
create table if not exists somarelectrodomesticos.social_posts (
  id             bigint generated by default as identity primary key,
  platform       text,
  image_url      text,
  link_url       text,
  caption        text,
  display_order  int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now()
);

-- 15) BANNERS / CONTENIDO PRINCIPAL -----------------------------------
create table if not exists somarelectrodomesticos.banners (
  id             bigint generated by default as identity primary key,
  type           text not null check (type in ('hero','featured_promotion','offers','final_cta','about')),
  eyebrow        text,
  title          text,
  subtitle       text,
  image_url      text,
  cta_label      text,
  cta_url        text,
  theme          text,
  display_order  int not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 16) ADMIN ACTIVITY LOG ----------------------------------------------
create table if not exists somarelectrodomesticos.admin_activity_log (
  id             bigint generated by default as identity primary key,
  admin_user_id  bigint references somarelectrodomesticos.admin_users(id) on delete set null,
  action         text not null,
  entity_type    text,
  entity_id      text,
  metadata       jsonb,
  created_at     timestamptz not null default now()
);
create index if not exists idx_activity_log_created on somarelectrodomesticos.admin_activity_log(created_at desc);

-- =====================================================================
--  TRIGGERS updated_at
-- =====================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'admin_users','site_settings','categories','brands','products',
    'product_installments','benefits','purchase_steps','testimonials','banners'
  ]
  loop
    execute format(
      'drop trigger if exists trg_set_updated_at on somarelectrodomesticos.%1$I;
       create trigger trg_set_updated_at before update on somarelectrodomesticos.%1$I
       for each row execute function somarelectrodomesticos.set_updated_at();', t);
  end loop;
end$$;

-- =====================================================================
--  ROW LEVEL SECURITY
-- =====================================================================
-- Activamos RLS en todas las tablas
do $$
declare t text;
begin
  foreach t in array array[
    'admin_users','site_settings','categories','brands','products','product_images',
    'product_features','product_specifications','product_installments','benefits',
    'purchase_steps','testimonials','stats','social_posts','banners','admin_activity_log'
  ]
  loop
    execute format('alter table somarelectrodomesticos.%I enable row level security;', t);
  end loop;
end$$;

-- ---- Lectura pública (anon + authenticated) de contenido ACTIVO -----
-- Tablas con columna is_active:
create policy anon_read_active_categories on somarelectrodomesticos.categories
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_brands on somarelectrodomesticos.brands
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_products on somarelectrodomesticos.products
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_benefits on somarelectrodomesticos.benefits
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_steps on somarelectrodomesticos.purchase_steps
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_testimonials on somarelectrodomesticos.testimonials
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_stats on somarelectrodomesticos.stats
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_social on somarelectrodomesticos.social_posts
  for select to anon, authenticated using (is_active = true);
create policy anon_read_active_banners on somarelectrodomesticos.banners
  for select to anon, authenticated using (is_active = true);

-- site_settings: singleton público (solo info comercial pública)
create policy anon_read_settings on somarelectrodomesticos.site_settings
  for select to anon, authenticated using (true);

-- Tablas hijas: lectura pública si el producto padre está activo
create policy anon_read_product_images on somarelectrodomesticos.product_images
  for select to anon, authenticated using (
    exists (select 1 from somarelectrodomesticos.products p where p.id = product_id and p.is_active = true));
create policy anon_read_product_features on somarelectrodomesticos.product_features
  for select to anon, authenticated using (
    exists (select 1 from somarelectrodomesticos.products p where p.id = product_id and p.is_active = true));
create policy anon_read_product_specs on somarelectrodomesticos.product_specifications
  for select to anon, authenticated using (
    exists (select 1 from somarelectrodomesticos.products p where p.id = product_id and p.is_active = true));
create policy anon_read_product_installments on somarelectrodomesticos.product_installments
  for select to anon, authenticated using (
    exists (select 1 from somarelectrodomesticos.products p where p.id = product_id and p.is_active = true));

-- ---- Acceso total para ADMIN autenticado (nunca USING(true) en escritura) ----
do $$
declare t text;
begin
  foreach t in array array[
    'site_settings','categories','brands','products','product_images',
    'product_features','product_specifications','product_installments','benefits',
    'purchase_steps','testimonials','stats','social_posts','banners'
  ]
  loop
    execute format(
      'create policy admin_all_%1$s on somarelectrodomesticos.%1$I
         for all to authenticated
         using (somarelectrodomesticos.is_admin())
         with check (somarelectrodomesticos.is_admin());', t);
  end loop;
end$$;

-- admin_users: solo admins ven/gestionan (sin lectura pública)
create policy admin_manage_admin_users on somarelectrodomesticos.admin_users
  for all to authenticated
  using (somarelectrodomesticos.is_admin())
  with check (somarelectrodomesticos.is_admin());

-- admin_activity_log: solo admins (insert/select)
create policy admin_activity_all on somarelectrodomesticos.admin_activity_log
  for all to authenticated
  using (somarelectrodomesticos.is_admin())
  with check (somarelectrodomesticos.is_admin());

-- =====================================================================
--  GRANTS (necesarios para que PostgREST use el schema)
--  RLS sigue gobernando el acceso real fila por fila.
-- =====================================================================
grant usage on schema somarelectrodomesticos to anon, authenticated, service_role;

grant select on all tables in schema somarelectrodomesticos to anon, authenticated;
grant insert, update, delete on all tables in schema somarelectrodomesticos to authenticated;
grant all on all tables in schema somarelectrodomesticos to service_role;

grant usage, select on all sequences in schema somarelectrodomesticos to authenticated, service_role;
grant execute on all functions in schema somarelectrodomesticos to anon, authenticated, service_role;

-- Privilegios por defecto para objetos futuros
alter default privileges in schema somarelectrodomesticos
  grant select on tables to anon, authenticated;
alter default privileges in schema somarelectrodomesticos
  grant insert, update, delete on tables to authenticated;
alter default privileges in schema somarelectrodomesticos
  grant usage, select on sequences to authenticated;

-- =====================================================================
--  EXPONER EL SCHEMA EN POSTGREST
--  Nota: además de esto, en el Dashboard de Supabase ir a
--  Project Settings → API → "Exposed schemas" y agregar
--  'somarelectrodomesticos'.  (Ver docs/ADMIN_SETUP.md)
-- =====================================================================
--  IMPORTANTE (self-hosted con varios proyectos): NO pisar la lista de
--  schemas ya expuestos. Se AGREGA 'somarelectrodomesticos' preservando los
--  demás (tradexpar, etc.).
do $$
declare
  current_val text;
  new_val text;
begin
  select split_part(cfg, '=', 2) into current_val
  from pg_roles r, unnest(coalesce(r.rolconfig, '{}'::text[])) cfg
  where r.rolname = 'authenticator' and cfg like 'pgrst.db_schemas=%'
  limit 1;

  if current_val is null or btrim(current_val) = '' then
    new_val := 'public, somarelectrodomesticos, storage';
  elsif position('somarelectrodomesticos' in current_val) > 0 then
    new_val := current_val;                                  -- ya expuesto
  else
    new_val := btrim(current_val) || ', somarelectrodomesticos';  -- agregar sin pisar
  end if;

  begin
    execute format('alter role authenticator set pgrst.db_schemas = %L', new_val);
    raise notice 'PostgREST db_schemas = %', new_val;
  exception when others then
    raise notice 'No se pudo alterar authenticator; exponé somarelectrodomesticos desde el Dashboard o con exponer-schema.sh (sin pisar los otros).';
  end;
end$$;
notify pgrst, 'reload config';

-- =====================================================================
--  STORAGE: bucket público de medios
--  (storage.objects es interno de Supabase; solo creamos bucket+policies)
-- =====================================================================
insert into storage.buckets (id, name, public)
values ('somar-media', 'somar-media', true)
on conflict (id) do nothing;

-- Lectura pública de los medios del bucket
drop policy if exists "somar_media_public_read" on storage.objects;
create policy "somar_media_public_read" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'somar-media');

-- Escritura/borrado solo administradores autorizados
drop policy if exists "somar_media_admin_write" on storage.objects;
create policy "somar_media_admin_write" on storage.objects
  for all to authenticated
  using (bucket_id = 'somar-media' and somarelectrodomesticos.is_admin())
  with check (bucket_id = 'somar-media' and somarelectrodomesticos.is_admin());

-- =====================================================================
--  FIN DE LA MIGRACIÓN
-- =====================================================================
